query GetReviewsBySlug($slug: String!) {
  reviews(
    where: { product: { slug: $slug } }
    stage: DRAFT
    orderBy: createdAt_DESC
  ) {
    content
    name
    rating
    headline
    createdAt
    id
  }
}

query GetRatingBySlug($slug: String!) {
  reviews(where: { product: { slug: $slug } }, stage: DRAFT) {
    rating
  }
}

query CheckProductReviewByEmail($email: String!, $slug: String!) {
  reviewsConnection(
    where: { email: $email, product: { slug: $slug } }
    stage: DRAFT
  ) {
    aggregate {
      count
    }
  }
}
