import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "./_components/ui/toaster";
import { ClientContext } from "./_components/contexts/ClientContext/ClientContext";
import { MainNav } from "./_components/MainNav";
import { LoaderProvider } from "./_components/contexts/LoaderContext.tsx/LoaderContext";
import { QueryProvider } from "./_components/contexts/QueryContext/QueryContext";
// import { CartProvider } from "./_components/contexts/CartContext/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientContext>
      <html lang="en">
        <body className={inter.className}>
          <QueryProvider>
            <LoaderProvider>
              <MainNav />
              {children}
              <Toaster />
            </LoaderProvider>
          </QueryProvider>
        </body>
      </html>
    </ClientContext>
  );
}
