import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "./_components/ui/toaster";
import { ClientContext } from "./_components/contexts/ClientContext/ClientContext";
import { MainNav } from "./_components/MainNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientContext>
      <html lang="en">
        <body className={inter.className}>
          <MainNav />
          {children}
          <Toaster />
        </body>
      </html>
    </ClientContext>
  );
}
