name: Notify Discord on Pull Request

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d @- $WEBHOOK_URL <<EOF
          {
            "content": "Nowy pull request został otwarty!\nTytuł: ${{ github.event.pull_request.title }}\nAutor: ${{ github.actor }}\nLink: ${{ github.event.pull_request.html_url }}"
          }
          EOF
