name: Discord notify DM
on:
  pull_request:
    types: [opened]

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_USER_ID: 401688734560550914

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4

      - run: |
          CHANNEL_ID=$(curl -s -X POST -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"recipient_id": "'$DISCORD_USER_ID'"}' \
          https://discord.com/api/v10/users/@me/channels | jq -r '.id')

          curl -X POST -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
          -H "Content-Type: application/json" \
          -d @- https://discord.com/api/v10/channels/$CHANNEL_ID/messages <<EOF
          {
            "content": "Nowy pull request został otwarty!\\nTytuł: ${{ github.event.pull_request.title }}\\nAutor: ${{ github.actor }}\\nLink: ${{ github.event.pull_request.html_url }}"
          }
          EOF
