name: Discord notify DM
on:
  pull_request:
    types: [opened, reopened]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Discord notify
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -d '{
                  "content": "🔔 **Pull Request Opened** 🔔\n
                  Repository: ${{ github.repository }}\n
                  PR Title: ${{ github.event.pull_request.title }}\n
                  PR Link: ${{ github.event.pull_request.html_url }}\n
                  Author: ${{ github.event.pull_request.user.login }}"
                }' \
            https://discord.com/api/v9/channels/$DISCORD_USER_ID/messages

      - name: Notify via Discord Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
                  "content": "🔔 **Pull Request Opened** 🔔\n
                  Repository: ${{ github.repository }}\n
                  PR Title: ${{ github.event.pull_request.title }}\n
                  PR Link: ${{ github.event.pull_request.html_url }}\n
                  Author: ${{ github.event.pull_request.user.login }}"
                }' \
            "$DISCORD_WEBHOOK"
