name: Discord Notify DM

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, reopened]

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Discord DM
        run: |
          # Step 1: Create DM channel with user
          CHANNEL_ID=$(curl -s -X POST \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"recipient_id\": \"$DISCORD_USER_ID\"}" \
            https://discord.com/api/v9/users/@me/channels | jq -r '.id')
          
          # Step 2: Send message to the DM channel
          curl -X POST \
            -H "Authorization: Bot $DISCORD_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
                  \"content\": \"🔔 **Pull Request Opened** 🔔\n
                  Repository: ${{ github.repository }}\n
                  PR Title: ${{ github.event.pull_request.title }}\n
                  PR Link: ${{ github.event.pull_request.html_url }}\n
                  Author: ${{ github.event.pull_request.user.login }}\"
                }" \
            https://discord.com/api/v9/channels/$CHANNEL_ID/messages

      - name: Notify via Discord Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{
            \"content\": \"🔔 **Pull Request Opened** 🔔\n
            Repository: ${{ github.repository }}\n
            PR Title: ${{ github.event.pull_request.title }}\n
            PR Link: ${{ github.event.pull_request.html_url }}\n
            Author: ${{ github.event.pull_request.user.login }}\"
          }" \
          "$DISCORD_WEBHOOK_URL"


