name: Discord Notify DM

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, reopened]

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Discord DM
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d @- $DISCORD_WEBHOOK_URL <<EOF
          {
            "content": "Nowy pull request został otwarty!\nTytuł: ${{ github.event.pull_request.title }}\nAutor: ${{ github.actor }}\nLink: ${{ github.event.pull_request.html_url }}"
          }
          EOF


