name: Display my name
on:
  pull_request:
    types: [opened]

env:
  MY_NAME: Marcin

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [2.x]
    steps:
      - uses: actions/checkout@v4

        run: echo "Moje imie to $MY_NAME"
