
name: Display my name

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [2.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Display my name
      run: echo ${{secrets.MY_NAME}}
